### ISSUE TITLE
Cannot use the ./jtag_bridge

### ISSUE THREAD

**Issue by binjon178** [quangdaovu/pulpino_jtag_bridge#1]
Hi sir, 
I also use the Oliminx Jtag and Arty code, but when I use the ./jtage_bridge
it shows:

Structs successfully initialized
Initializing USB device
Connected to libftdi driver.
Initializing USB device
Open MPSSE mode returned: OK
Enumerating JTAG chain...
WARNING: maximum supported devices on JTAG chain (1024) exceeded.

Devices on JTAG chain:
Index	Name		ID Code		IR Length
----------------------------------------------------------------

It seems the jtag is connected but it cannot figured by Arty FPGA !
Could you help me to add more README or point out the error ?

**Comment by quangdaovu** [comment]
Hi, 
I was pretty busy at work at the time that I commited this code. I'll add more details whenever I have time, please pardon me.
Can you give me some information about the hardware connection between Olimex JTAG & the FPGA board? Is the arty code mine?

**Comment by binjon178** [comment]
1. info. between
[rvdev2@~/test/pulp_v3/pulpino_jtag_bridge]$ lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 006: ID 045e:07b2 Microsoft Corp. 
Bus 001 Device 002: ID 15ba:002b Olimex Ltd. ARM-USB-OCD-H JTAG+RS232
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

2. Yes, the code is almost the same, but I've add spi_oen to make FLASH boot-code. 

I've use oscilloscope to find out the tck has transmit signal for a while, thank you for reply !!

**Comment by quangdaovu** [comment]
Humm, this isn't what I wanted. I'm expecting something like this: https://imgur.com/a/R8nxceL. I couldn't give you exactly my connection right now since the kit isn't here, by the way you can find the pin definition in xdc file. Please make sure that the connection between FPGA board & Olimex JTAG bridge is correct.

**Comment by binjon178** [comment]
Mine is here, I use PMOD JD instead of JC
[https://imgur.com/a/pHVrtSg](https://imgur.com/a/pHVrtSg)

**Comment by quangdaovu** [comment]
I honestly couldn't tell anything with that picture (mine has 7 signals: 2 for power, 5 others are trstn_i, td_i, tck_i, tms_i and td_o; meanwhile you have like 12 signals). Please give me the connection diagram, your FPGA top level and XDC constrain file.

**Comment by binjon178** [comment]
Hi sir, 
I've used ubuntu to build up the ftdi driver again, and it seems we find the Pulpino core which is listening !
Is it work now ?
[https://imgur.com/a/EzLfmeq](https://imgur.com/a/EzLfmeq)

**Comment by quangdaovu** [comment]
Yes it is. You can take a look at this, it might help.

https://imgur.com/a/yod112H

**Comment by binjon178** [comment]
Hi sir, 
Could you advise the version of riscv gdb tool you use ?
now it seems the gdb is not connected 
[https://imgur.com/a/5NHta7E](https://imgur.com/a/5NHta7E)

**Comment by quangdaovu** [comment]
It already been shown in my previous screenshot, v7.11.50.

I think any version prior to 2018 of https://github.com/riscv/riscv-gnu-toolchain is ok (since my last build was 2017/12/21).

**Comment by binjon178** [comment]
Hi @quangdaovu 

Thanks you for help !!

I checkout the old version of risc-gnu-toolchain as "HEAD detached at v20171107"
and then replace the gdb as `https://github.com/riscv/riscv-binutils-gdb/tree/2a3cd80`

It works now !!! Thanks again !!

**Comment by binjon178** [comment]
Hello, 
I found out in the same situation, continue will not stop at the break point.
e.g.: "b 22" for helloworkd.c. 

Do you see the same situation for gdb not working ?
Or you only can load elf to i/dram and run ?

Thanks !!

**Comment by quangdaovu** [comment]
Hi, so sorry for my late reply, I had some trouble with my health lately.

About your issue, please accept my apology again because of the instructions earlier, that was totally wrong. I didn't work with pulpino for around 1 year so I almost forgot everything about it already.

Ok now to the problem. To be honest I have no idea what's going on with the MCU. If you manually set the PC to 0x80 it will never work. There is a workaround method is set the PC by software. Therefore I leave 1 option in boot_code for it. So, you have to do following steps in order to debug new program in PULPino:

1. Connect UART first (baudrate is 115200), you will need it later.
2. Start jtag_bridge, connect gdb with jtag_bridge.
3. Use file instead of load directly. For example `file helloworld/helloworld.elf`, wait for gdb to load the file, and then `load`. By this way you can place the breakpoint using b + line number.
4. Set the breakpoint as your wish.
5. Set PC to 0x8080 (which is the execution address of boot_code).
6. Continue in gdb by using c.
7. In terminal, press anykey first to stop the countdown, then choose 1.
8. Here you go.

**Comment by binjon178** [comment]
Hi, 

Thanks for update, 
I've followed the steps above, but now stuck in the step 7, which the boot code go to the instruction ram directly as [https://imgur.com/agraPYK](https://imgur.com/agraPYK).

The gdb showed as [https://imgur.com/yIXmkp8](https://imgur.com/yIXmkp8)

I think the data of rom is not aligned. Or  @quangdaovu have any idea ?

Thank you so much !!

**Comment by quangdaovu** [comment]
Hi, 

You have to skip the countdown and select option 1 in following menu. If the countdown finished it will automatically **get** instruction & data memory content from SPI Flash, meanwhile option 1 run straight from current instruction & data memory.

**Comment by binjon178** [comment]
Hi @quangdaovu, 

Thank you for help, 
I've repeated the steps 1~8. 
**I've pulled the SW3 for fetch_en signal before step 7**, to make the terminal start to count down and press 1 to run straight from current instruction and data memory.

The terminal shows [https://imgur.com/HS38DmO](https://imgur.com/HS38DmO)
It only gave 4 options and **have no further uart print out result from my loading elf in step 3**.

But the gdb shows [https://imgur.com/6J3gA32](https://imgur.com/6J3gA32)

The question is :
Q1: It only shows the break point in the gdb, but the terminal doesn't show any message, is it the same in your place ?
Q2: how can I show "helloworld " in the terminal side ?

Thanks again !!

**Comment by binjon178** [comment]
Hi @quangdaovu 

I finally figured out the issue. The helloworld in gdb server doesn't include the uart fundamental component thus never prints in the uart terminal. 

I've followed the boot_code.v's uart command instead of printf. It works well now.

Thousands thanks, dude !!
